openssh: set kex->sessin_id via sshbuf_put in ssh-cavs
The kex->session_id has been replaced from u_char * to sshbuf and
kex->session_id_len has been removed in openssh 8.5[1]. Update ssh-cavs
to adapt it.

Fixes:
ssh-cavs.c:198:12: error: 'struct kex' has no member named 'session_id_len'; did you mean 'session_id'?
  198 |  ssh->kex->session_id_len = test->session_id_len;
      |            ^~~~~~~~~~~~~~
      |            session_id

[1] https://github.com/openssh/openssh-portable/commit/39be3dc209f28f9c1ebfeba42adde8963b01e1cd

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Jason Wessel <jason.wessel@windriver.com>